import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from '../components/Navbar'
import { Container } from '@chakra-ui/react';
import video from '../public/League of Legends.webm';
// import { background, Box } from '@chakra-ui/react'
import ReactPlayer from 'react-player'

export default function Home() {
  return (
    <div className={styles.container} >
      <Head>
        <title>League Of Legends</title>
        <meta name="description" content="Generated by Kankuro" />
        <link rel="icon" href="/icons8-league-of-legends-color-32.ico" />
      </Head>
         <Navigation />
      <main className={styles.main}>
        <Container width='100%' className={styles.Headcontainer}>
         <Container maxW='container.sm' width='90%' className={styles.Fcontainer}>
           
              <video src={video} autoPlay muted loop  className={styles.videoSize}/>
          
          <div className={styles.textTexture}>
          <h1 className={styles.title}>
          <a href="/"> League <span>Of</span> Legends</a>
          </h1>
       </div>
         </Container>
        </Container>
       
       <Container width='100%' className={styles.champions}>
         <div className={styles.choose}>
          <h4 className={styles.miniText}>CHOOSE YOUR</h4>
          <h1 className={styles.largeText}>CHAMPION</h1>
         </div>

        <div className={styles.paragraph}>
          <p>
            Whether you like to dive straight into the fray, support your teammates, or something in between, there’s a spot for you on the Rift.
          </p>
        </div>
        <a href='/champions' className={styles.button} role="button">Discover More Champions</a>

        <div className={styles.CategoriesChamps}>

            <div className={styles.champQuote}>
              <p></p>
            </div> 
            
            <div className={styles.champPic}>
                
            </div>
          </div>
        </Container>




        {/* <div className={styles.video}>
          <video src={video} autoPlay loop  className={styles.videoSize}/>
        </div> */}

      
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/icons8-league-of-legends-color-32.png" alt="Vercel Logo" width={18} height={18} />
          </span>
        </a>
      </footer>
    </div>
  )
}
