import Image from 'next/image';
import Head from 'next/head'
import Navbar from '../../components/Navbar'
import axios from 'axios';
import styles from '../../styles/Home.module.css'
import { useEffect, useState } from 'react';
import Champion from '../../components/Champion';
import { Heading , Box , Flex , Input , Stack , IconButton , useToast } from '@chakra-ui/react';




export default function Champions(){
    const [champions ,setChampions] = useState([]);


    useEffect(()=>{
        axios.get('http://ddragon.leagueoflegends.com/cdn/11.14.1/data/en_US/champion.json')
        .then(result=>{
           
           console.log(result.data.data)
            const obj = result.data.data
                  var champs = [];
                for (const key in obj) {
                  if (Object.hasOwnProperty.call(obj, key)) {
                    var element = obj[key];
                    champs.push(element)
                  }
                   setChampions(champs)
                }

        })
        },[])


  return (
    <Flex direction="column" justify="center" align="center" className={styles.background}>
      <Head>
        <title>League Of Legends</title>
        <meta name="description" content="Generated by Kankuro" />
        <link rel="icon" href="/icons8-league-of-legends-color-32.ico" />
      </Head>
      <Navbar />
     <Box mb={4} flexDirection="column" align="center" justify="center" py={8}>
      <Heading as="h1" size="2x1" mb={8} className={styles.tit}>Champions</Heading>
      <Champion champions={champions} ></Champion>
     </Box>
     <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/icons8-league-of-legends-color-32.png" alt="Vercel Logo" width={18} height={18} />
          </span>
        </a>
      </footer>
    </Flex>
  )

}


